import type { Job } from "./types"

export const jobs: Job[] = [
  {
    id: "job1",
    title: "Gaming Highlights for TikTok and YouTube Shorts",
    description: "Looking for editors to create short-form content from my Valorant and Apex Legends gameplay.",
    longDescription:
      "I stream Valorant and Apex Legends 5 days a week and need help turning my best moments into viral short-form content. I'm looking for editors who understand gaming content and can identify the most entertaining moments. Your clips should capture exciting plays, funny reactions, and epic fails that will resonate with gaming audiences.",
    creatorName: "GamerPro99",
    status: "Open",
    payRate: 50,
    postedDate: "May 1, 2023",
    deadline: "Ongoing",
    platforms: ["TikTok", "YouTube Shorts"],
    contentType: "Gaming (FPS)",
    contentLinks: ["https://www.twitch.tv/gamerpro99", "https://www.youtube.com/gamerpro99"],
    clippers: 12,
    totalViews: 2500000,
    totalLikes: 320000,
    requirements: {
      clip: [
        "15-60 seconds in length",
        "Must include my face cam reaction",
        "Add subtitles for important dialogue",
        "Include my channel name in the video",
        "Music and sound effects are encouraged",
      ],
      submission: [
        "Submit link to published clip",
        "Include screenshot of analytics after 48 hours",
        "Tag me in the description with @GamerPro99",
        "Use relevant gaming hashtags",
      ],
      notAllowed: [
        "No clickbait that misrepresents the content",
        "No inappropriate edits or added commentary",
        "No reusing clips that have already been posted",
        "No posting to platforms not specified in the job",
      ],
    },
    leaderboard: [
      {
        clipperName: "EditMaster",
        platform: "TikTok",
        views: 850000,
        likes: 120000,
        earnings: 425.0,
        clipUrl: "https://tiktok.com/clip1",
      },
      {
        clipperName: "ViralClips",
        platform: "YouTube Shorts",
        views: 650000,
        likes: 85000,
        earnings: 325.0,
        clipUrl: "https://youtube.com/shorts/clip2",
      },
      {
        clipperName: "ShortFormPro",
        platform: "TikTok",
        views: 450000,
        likes: 62000,
        earnings: 225.0,
        clipUrl: "https://tiktok.com/clip3",
      },
      {
        clipperName: "ClipGenius",
        platform: "YouTube Shorts",
        views: 320000,
        likes: 41000,
        earnings: 160.0,
        clipUrl: "https://youtube.com/shorts/clip4",
      },
      {
        clipperName: "ContentWizard",
        platform: "TikTok",
        views: 230000,
        likes: 28000,
        earnings: 115.0,
        clipUrl: "https://tiktok.com/clip5",
      },
    ],
  },
  {
    id: "job2",
    title: "Cooking Tutorial Clips for Instagram Reels",
    description: "Need short, engaging clips from my long-form cooking videos for Instagram Reels.",
    longDescription:
      "I create detailed cooking tutorials on YouTube, but need help converting these into bite-sized, engaging clips for Instagram Reels. The ideal clips will showcase the most visually appealing moments of the cooking process, quick tips, or satisfying final reveals of the dishes. Looking for editors who understand food content and can make mouth-watering short-form videos.",
    creatorName: "ChefMaria",
    status: "Open",
    payRate: 60,
    postedDate: "April 15, 2023",
    deadline: "June 30, 2023",
    platforms: ["Instagram Reels"],
    contentType: "Cooking/Food",
    contentLinks: ["https://www.youtube.com/chefmaria", "https://www.instagram.com/chefmaria"],
    clippers: 8,
    totalViews: 1800000,
    totalLikes: 240000,
    requirements: {
      clip: [
        "15-30 seconds in length",
        "Focus on visually appealing moments",
        "Add text overlays for recipe steps",
        "Use food-appropriate music",
        "Include my branding watermark",
      ],
      submission: [
        "Submit link to published Reel",
        "Include analytics after 72 hours",
        "Tag @ChefMaria in the post",
        "Use hashtags #foodtok #recipeshorts",
      ],
      notAllowed: [
        "No altering cooking instructions",
        "No misleading ingredient information",
        "No excessive effects that distract from the food",
        "No posting to other platforms without permission",
      ],
    },
    leaderboard: [
      {
        clipperName: "FoodieEditor",
        platform: "Instagram Reels",
        views: 620000,
        likes: 95000,
        earnings: 372.0,
        clipUrl: "https://instagram.com/reel1",
      },
      {
        clipperName: "ReelMaster",
        platform: "Instagram Reels",
        views: 480000,
        likes: 72000,
        earnings: 288.0,
        clipUrl: "https://instagram.com/reel2",
      },
      {
        clipperName: "ShortChef",
        platform: "Instagram Reels",
        views: 350000,
        likes: 48000,
        earnings: 210.0,
        clipUrl: "https://instagram.com/reel3",
      },
      {
        clipperName: "FoodClips",
        platform: "Instagram Reels",
        views: 210000,
        likes: 32000,
        earnings: 126.0,
        clipUrl: "https://instagram.com/reel4",
      },
      {
        clipperName: "RecipeShorts",
        platform: "Instagram Reels",
        views: 140000,
        likes: 19000,
        earnings: 84.0,
        clipUrl: "https://instagram.com/reel5",
      },
    ],
  },
  {
    id: "job3",
    title: "Educational Content for TikTok",
    description: "Convert my science lectures into engaging, educational TikTok clips.",
    longDescription:
      "I'm a science educator looking to reach a younger audience on TikTok. I need help converting my detailed lecture videos into engaging, informative short clips that explain complex scientific concepts in an accessible way. The ideal clips will be attention-grabbing, educational, and leave viewers wanting to learn more.",
    creatorName: "ScienceWithSam",
    status: "Open",
    payRate: 45,
    postedDate: "May 10, 2023",
    deadline: "July 15, 2023",
    platforms: ["TikTok"],
    contentType: "Educational/Science",
    contentLinks: ["https://www.youtube.com/sciencewithsam", "https://www.sciencewithsam.com/lectures"],
    clippers: 5,
    totalViews: 950000,
    totalLikes: 180000,
    requirements: {
      clip: [
        "30-60 seconds in length",
        "Must maintain scientific accuracy",
        "Add engaging visuals or animations",
        "Include clear text explanations",
        "End with a hook or question to encourage engagement",
      ],
      submission: [
        "Submit link to published TikTok",
        "Include analytics after 48 hours",
        "Tag @ScienceWithSam",
        "Use hashtags #LearnOnTikTok #ScienceTok",
      ],
      notAllowed: [
        "No oversimplification that leads to inaccuracy",
        "No clickbait or misleading information",
        "No political commentary",
        "No excessive effects that distract from the educational content",
      ],
    },
    leaderboard: [
      {
        clipperName: "EduClips",
        platform: "TikTok",
        views: 380000,
        likes: 85000,
        earnings: 171.0,
        clipUrl: "https://tiktok.com/clip1",
      },
      {
        clipperName: "ScienceTok",
        platform: "TikTok",
        views: 290000,
        likes: 62000,
        earnings: 130.5,
        clipUrl: "https://tiktok.com/clip2",
      },
      {
        clipperName: "LearnShorts",
        platform: "TikTok",
        views: 180000,
        likes: 35000,
        earnings: 81.0,
        clipUrl: "https://tiktok.com/clip3",
      },
      {
        clipperName: "KnowledgeClips",
        platform: "TikTok",
        views: 100000,
        likes: 22000,
        earnings: 45.0,
        clipUrl: "https://tiktok.com/clip4",
      },
    ],
  },
  {
    id: "job4",
    title: "Fitness Motivation Clips for All Platforms",
    description: "Create motivational fitness clips from my workout videos for multiple platforms.",
    longDescription:
      "I'm a fitness instructor looking for editors to create motivational clips from my workout videos. These clips should inspire people to start their fitness journey, showcase proper form for exercises, and highlight transformation stories. I'm open to distribution across all major short-form platforms to maximize reach.",
    creatorName: "FitWithJamie",
    status: "Closed",
    payRate: 55,
    postedDate: "March 5, 2023",
    deadline: "April 30, 2023",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    contentType: "Fitness/Wellness",
    contentLinks: ["https://www.youtube.com/fitwithjamie", "https://www.instagram.com/fitwithjamie"],
    clippers: 15,
    totalViews: 3200000,
    totalLikes: 420000,
    requirements: {
      clip: [
        "15-60 seconds in length",
        "Include motivational quotes or text overlays",
        "Show proper exercise form",
        "Add energetic music",
        "Include before/after transformations when available",
      ],
      submission: [
        "Submit links to all platforms where posted",
        "Include analytics after 1 week",
        "Tag @FitWithJamie on all platforms",
        "Use hashtags #FitnessMotivation #WorkoutTips",
      ],
      notAllowed: [
        "No promotion of unhealthy fitness practices",
        "No body shaming content",
        "No misrepresentation of results",
        "No excessive filters that alter body appearance",
      ],
    },
    leaderboard: [
      {
        clipperName: "FitEditor",
        platform: "TikTok",
        views: 950000,
        likes: 140000,
        earnings: 522.5,
        clipUrl: "https://tiktok.com/clip1",
      },
      {
        clipperName: "MotivationClips",
        platform: "Instagram Reels",
        views: 780000,
        likes: 110000,
        earnings: 429.0,
        clipUrl: "https://instagram.com/reel1",
      },
      {
        clipperName: "WorkoutShorts",
        platform: "YouTube Shorts",
        views: 650000,
        likes: 85000,
        earnings: 357.5,
        clipUrl: "https://youtube.com/shorts/clip1",
      },
      {
        clipperName: "FitnessReels",
        platform: "Instagram Reels",
        views: 520000,
        likes: 68000,
        earnings: 286.0,
        clipUrl: "https://instagram.com/reel2",
      },
      {
        clipperName: "GymTok",
        platform: "TikTok",
        views: 300000,
        likes: 42000,
        earnings: 165.0,
        clipUrl: "https://tiktok.com/clip2",
      },
    ],
  },
]
